<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FlowOS.Domain\FlowOS.Domain.csproj" />
    <ProjectReference Include="..\FlowOS.Events\FlowOS.Events.csproj" /> <!-- Needed for IEvent -->
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.2.0" /> <!-- Needed for INotification -->
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>