services:
  flowos-api:
    image: flowos-api
    build:
      context: .
      dockerfile: src/FlowOS.Api/Dockerfile 
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
    volumes:
      - ./flowos-config:/app/flowos-config

  flowos-dashboard:
    image: flowos-dashboard
    build:
      context: .
      dockerfile: docker/dashboard.Dockerfile
    environment:
      - VITE_API_TARGET=${VITE_API_TARGET}
    depends_on:
      - flowos-api

  flowos-mcp:
    image: flowos-mcp
    build:
      context: .
      dockerfile: src/FlowOS.MCP/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
    stdin_open: true # docker run -i
    tty: true        # docker run -t 
 

volumes:
  db-data:
