// <auto-generated />
using System;
using System.Collections.Generic;
using FlowOS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowOS.Infrastructure.Migrations
{
    [DbContext(typeof(FlowOSDbContext))]
    [Migration("20260924220247_AddWorkflowClassChangeLogAndDeprecation")]
    partial class AddWorkflowClassChangeLogAndDeprecation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowOS.Application.ReadModels.AgentInsightReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContextObjective")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Insight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("AgentInsights");
                });

            modelBuilder.Entity("FlowOS.Core.Common.Models.CapabilityBindingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthRef")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CapabilityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("RequestSchemaVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResponseSchemaVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RetryPolicy")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeoutMs")
                        .HasColumnType("integer");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("TenantId", "CapabilityName")
                        .IsUnique();

                    b.ToTable("CapabilityBindings", (string)null);
                });

            modelBuilder.Entity("FlowOS.Core.Common.Models.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("TenantId", "OperationName", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("FlowOS.Core.Common.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeadLetter")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextRetryUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProcessedOnUtc", "OccurredOnUtc");

                    b.HasIndex("IsDeadLetter", "ProcessedOnUtc", "NextRetryUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("FlowOS.Core.Common.Models.PluginBindingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BindingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BindingType", "IsEnabled");

                    b.HasIndex("TenantId", "BindingType", "SourceName")
                        .IsUnique();

                    b.ToTable("PluginBindings", (string)null);
                });

            modelBuilder.Entity("FlowOS.Core.Common.Models.WorkflowTimerJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggerEventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("IsProcessed", "DueTimeUtc");

                    b.ToTable("WorkflowTimerJobs", (string)null);
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.AgentExecutionRecord", b =>
                {
                    b.Property<Guid>("ExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Claimant")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ContextBindingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContextBindingRevisionId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ContextVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionOutcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ObservedOutcome")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("OutcomeEvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("OutcomeMatchedSuggestion")
                        .HasColumnType("boolean");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OverriddenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OverrideActor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OverrideEvent")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OverrideReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ParkReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PromptAlias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderAlias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RuntimeIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RuntimeVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SanitizedFailure")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("SuggestedEvent")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasCommitted")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasOverridden")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasParked")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("WorkflowDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WorkflowDefinitionVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("ExecutionId");

                    b.HasIndex("JobId");

                    b.HasIndex("TenantId", "StartedAtUtc")
                        .HasDatabaseName("IX_AgentExecutionRecords_Tenant_Time");

                    b.HasIndex("TenantId", "WorkflowInstanceId", "StartedAtUtc")
                        .HasDatabaseName("IX_AgentExecutionRecords_Tenant_Instance_Time");

                    b.ToTable("AgentExecutionRecords", (string)null);
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.AgentTaskJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveKey")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("AllowAutoCommit")
                        .HasColumnType("boolean");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClaimExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Claimant")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Objective")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RequestedAgentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequireAgentActor")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActiveKey")
                        .IsUnique()
                        .HasFilter("\"ActiveKey\" IS NOT NULL");

                    b.HasIndex("Status", "ClaimExpiresAtUtc")
                        .HasDatabaseName("IX_AgentTaskJobs_ExpiredClaims");

                    b.HasIndex("Status", "DueAtUtc", "RequestedAtUtc")
                        .HasDatabaseName("IX_AgentTaskJobs_Polling");

                    b.HasIndex("TenantId", "WorkflowInstanceId", "StepId");

                    b.ToTable("AgentTaskJobs", (string)null);
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.DistributedLease", b =>
                {
                    b.Property<string>("LeaseKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("LeaseKey");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("DistributedLeases", (string)null);
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.EventDefinition", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PayloadSchema")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("EventId", "TenantId");

                    b.ToTable("EventDefinitions");
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.HostedLlmDailyUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedRequests")
                        .HasColumnType("integer");

                    b.Property<int>("FinalizedRequests")
                        .HasColumnType("integer");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("ReservedRequests")
                        .HasColumnType("integer");

                    b.Property<int>("SuccessfulRequests")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("UsageDateUtc")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UsageDateUtc");

                    b.HasIndex("TenantId", "UsageDateUtc", "Model")
                        .IsUnique();

                    b.ToTable("HostedLlmDailyUsages", (string)null);
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.StateMachineDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InitialState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("States")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EntityType", "Version");

                    b.ToTable("StateMachineDefinitions");
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Active");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Managed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebhookSigningSecret")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("TenantId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.TenantApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasDefaultValue("Default Application");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Production");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaskedKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ApplicationName");

                    b.ToTable("TenantApiKeys", (string)null);
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("TenantUsers", (string)null);
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.TenantUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantUserId", "RoleId")
                        .IsUnique();

                    b.ToTable("TenantUserRoles", (string)null);
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.WorkflowActionExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OutboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestPayloadSnippet")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ResponseSnippet")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Target")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggerPhase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("TenantId", "WorkflowInstanceId", "ExecutedAtUtc");

                    b.ToTable("WorkflowActionExecutionLogs", (string)null);
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.WorkflowClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeLog")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DeprecationMigrationTargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeprecationReason")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("WorkflowClasses");
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.WorkflowContextBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveRevisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContextType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DraftRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedContextType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Draft");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedContextType")
                        .IsUnique();

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("WorkflowContextBindings", (string)null);
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.WorkflowContextBindingRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceWorkflowClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceWorkflowClassVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("StateMachineDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkflowDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceWorkflowClassId");

                    b.HasIndex("StateMachineDefinitionId")
                        .IsUnique()
                        .HasFilter("\"StateMachineDefinitionId\" IS NOT NULL");

                    b.HasIndex("WorkflowDefinitionId")
                        .IsUnique()
                        .HasFilter("\"WorkflowDefinitionId\" IS NOT NULL");

                    b.HasIndex("BindingId", "Revision")
                        .IsUnique();

                    b.HasIndex("BindingId", "Status");

                    b.ToTable("WorkflowContextBindingRevisions", (string)null);
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.WorkflowContextSnapshot", b =>
                {
                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessMetadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CanonicalData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("ContextBindingRevisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalEntityId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkflowInstanceId");

                    b.HasIndex("ContextBindingRevisionId");

                    b.HasIndex("TenantId", "ContextBindingRevisionId");

                    b.HasIndex("WorkflowInstanceId", "TenantId")
                        .IsUnique();

                    b.HasIndex("TenantId", "SourceSystem", "ExternalEntityId");

                    b.ToTable("WorkflowContextSnapshots", (string)null);
                });

            modelBuilder.Entity("FlowOS.Events.Models.DomainEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.ToTable("Events", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("DomainEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FlowOS.Notifications.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("TenantId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("FlowOS.Security.Models.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Policies", (string)null);
                });

            modelBuilder.Entity("FlowOS.Security.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("FlowOS.Workflows.Domain.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessRoles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ContextBindingRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SourceWorkflowClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("StartStepId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StateMachineDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContextBindingRevisionId");

                    b.HasIndex("SourceWorkflowClassId");

                    b.HasIndex("StateMachineDefinitionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name", "Version")
                        .IsUnique();

                    b.ToTable("WorkflowDefinitions", (string)null);
                });

            modelBuilder.Entity("FlowOS.Workflows.Domain.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveStepIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedParallelStepIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CurrentStepId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParentStepId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentWorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("PathTravelCounts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleAssignments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkflowDefinitionId");

                    b.HasIndex("TenantId", "ParentWorkflowInstanceId", "ParentStepId");

                    b.ToTable("WorkflowInstances", (string)null);
                });

            modelBuilder.Entity("FlowOS.Agents.Events.AgentInsightGenerated", b =>
                {
                    b.HasBaseType("FlowOS.Events.Models.DomainEvent");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextObjective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Insight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("AgentInsightGenerated");
                });

            modelBuilder.Entity("FlowOS.Events.Models.StandardEvent", b =>
                {
                    b.HasBaseType("FlowOS.Events.Models.DomainEvent");

                    b.HasDiscriminator().HasValue("StandardEvent");
                });

            modelBuilder.Entity("FlowOS.Events.Models.TaskCompleted", b =>
                {
                    b.HasBaseType("FlowOS.Events.Models.DomainEvent");

                    b.Property<Guid>("CompletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasDiscriminator().HasValue("TaskCompleted");
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.StateMachineDefinition", b =>
                {
                    b.OwnsMany("FlowOS.Domain.ValueObjects.StateTransition", "Transitions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Constraints")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValueSql("'{}'");

                            b1.Property<string>("EventId")
                                .HasColumnType("text");

                            b1.Property<string>("FromState")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("StateMachineDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ToState")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TriggerEventType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("StateMachineDefinitionId");

                            b1.ToTable("StateTransition");

                            b1.WithOwner()
                                .HasForeignKey("StateMachineDefinitionId");
                        });

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.TenantUser", b =>
                {
                    b.HasOne("FlowOS.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.WorkflowContextBindingRevision", b =>
                {
                    b.HasOne("FlowOS.Domain.Entities.WorkflowContextBinding", null)
                        .WithMany()
                        .HasForeignKey("BindingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowOS.Domain.Entities.WorkflowClass", null)
                        .WithMany()
                        .HasForeignKey("SourceWorkflowClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowOS.Domain.Entities.StateMachineDefinition", null)
                        .WithMany()
                        .HasForeignKey("StateMachineDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlowOS.Workflows.Domain.WorkflowDefinition", null)
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FlowOS.Domain.Entities.WorkflowContextSnapshot", b =>
                {
                    b.HasOne("FlowOS.Domain.Entities.WorkflowContextBindingRevision", null)
                        .WithMany()
                        .HasForeignKey("ContextBindingRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowOS.Workflows.Domain.WorkflowInstance", null)
                        .WithOne()
                        .HasForeignKey("FlowOS.Domain.Entities.WorkflowContextSnapshot", "WorkflowInstanceId", "TenantId")
                        .HasPrincipalKey("FlowOS.Workflows.Domain.WorkflowInstance", "Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowOS.Workflows.Domain.WorkflowDefinition", b =>
                {
                    b.HasOne("FlowOS.Domain.Entities.WorkflowClass", null)
                        .WithMany()
                        .HasForeignKey("SourceWorkflowClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlowOS.Domain.Entities.StateMachineDefinition", null)
                        .WithMany()
                        .HasForeignKey("StateMachineDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("FlowOS.Workflows.Domain.WorkflowStepDefinition", "Steps", b1 =>
                        {
                            b1.Property<Guid>("WorkflowDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Actor")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AgentPrompt")
                                .HasColumnType("text");

                            b1.Property<string>("AgentProvider")
                                .HasColumnType("text");

                            b1.Property<string>("AgentTools")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<List<string>>("AllowedRoles")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<string>("Branches")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Conditions")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DecisionGuideline")
                                .HasColumnType("text");

                            b1.Property<string>("DecisionProvider")
                                .HasColumnType("text");

                            b1.Property<string>("EventRequiredCapabilities")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("InboundSteps")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("JoinPolicy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("NextSteps")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("OnEntry")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("OnExit")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("OnFailure")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PathLimits")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("RequiredCapabilities")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StepId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("StepType")
                                .HasColumnType("integer");

                            b1.HasKey("WorkflowDefinitionId", "Id");

                            b1.ToTable("WorkflowDefinitions");

                            b1.ToJson("Steps");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowDefinitionId");

                            b1.OwnsOne("FlowOS.Workflows.Domain.StepAutoCommitDefinition", "AutoCommit", b2 =>
                                {
                                    b2.Property<Guid>("WorkflowStepDefinitionWorkflowDefinitionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("WorkflowStepDefinitionId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("AllowedEvents")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<double>("MinConfidence")
                                        .HasColumnType("double precision");

                                    b2.HasKey("WorkflowStepDefinitionWorkflowDefinitionId", "WorkflowStepDefinitionId");

                                    b2.ToTable("WorkflowDefinitions");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkflowStepDefinitionWorkflowDefinitionId", "WorkflowStepDefinitionId");
                                });

                            b1.OwnsOne("FlowOS.Workflows.Domain.StepSlaDefinition", "Sla", b2 =>
                                {
                                    b2.Property<Guid>("WorkflowStepDefinitionWorkflowDefinitionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("WorkflowStepDefinitionId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Duration")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("EscalationRole")
                                        .HasColumnType("text");

                                    b2.Property<string>("EscalationStepId")
                                        .HasColumnType("text");

                                    b2.Property<bool>("IsInterrupting")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("Reminders")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("TimeoutEvent")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("WorkflowStepDefinitionWorkflowDefinitionId", "WorkflowStepDefinitionId");

                                    b2.ToTable("WorkflowDefinitions");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkflowStepDefinitionWorkflowDefinitionId", "WorkflowStepDefinitionId");
                                });

                            b1.OwnsOne("FlowOS.Workflows.Domain.SubWorkflowReferenceDefinition", "SubWorkflow", b2 =>
                                {
                                    b2.Property<Guid>("WorkflowStepDefinitionWorkflowDefinitionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("WorkflowStepDefinitionId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("InputMapping")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("OutputMapping")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int?>("Version")
                                        .HasColumnType("integer");

                                    b2.Property<Guid?>("WorkflowClassId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid?>("WorkflowDefinitionId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("WorkflowName")
                                        .HasColumnType("text");

                                    b2.HasKey("WorkflowStepDefinitionWorkflowDefinitionId", "WorkflowStepDefinitionId");

                                    b2.ToTable("WorkflowDefinitions");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkflowStepDefinitionWorkflowDefinitionId", "WorkflowStepDefinitionId");
                                });

                            b1.Navigation("AutoCommit");

                            b1.Navigation("Sla");

                            b1.Navigation("SubWorkflow");
                        });

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
