using FlowOS.Application.Behaviors;
using FlowOS.Application.Common.Interfaces;
using FlowOS.Application.Services;
using FlowOS.Application.Commands.Governance;
using FlowOS.Core.Interfaces;
using FlowOS.Domain.Services;
using FlowOS.Domain.Validation;
using FlowOS.Infrastructure;
using FlowOS.Infrastructure.Persistence;
using FlowOS.Infrastructure.Services;
using FlowOS.StateMachines.Engine;
using FlowOS.Workflows.Engine;
using FlowOS.MCP.Models;
using FlowOS.MCP.Server;
using FlowOS.MCP.Services;
using FlowOS.MCP.Tools;
using FlowOS.Notifications.Application;
using FlowOS.Security.Interfaces;
using FlowOS.Security.Policies;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Security.Cryptography;
using System.Text;

namespace FlowOS.MCP;

public partial class Program
{
    static async Task Main(string[] args)
    {
        var transport = Environment.GetEnvironmentVariable("MCP_TRANSPORT") ?? "stdio";
        if (string.Equals(transport, "http", StringComparison.OrdinalIgnoreCase))
            await RunHttpAsync(args);
        else
            await RunStdioAsync(args);
    }

    static async Task RunStdioAsync(string[] args)
    {
        var host = Host.CreateDefaultBuilder(args)
            .ConfigureServices((context, services) =>
            {
                AddFlowOsMcpServices(services);
                services.AddSingleton<McpServer>();
                services.AddHostedService<McpHostedService>();
            })
            .ConfigureLogging(logging =>
            {
                logging.ClearProviders();
                logging.AddDebug();
                logging.AddConsole(options => options.LogToStandardErrorThreshold = LogLevel.Trace);
            })
            .Build();

        await InitializePostgresPersistenceAsync(host.Services);
        await host.RunAsync();
    }

    static async Task RunHttpAsync(string[] args)
    {
        var app = BuildHttpApp(args);
        await InitializePostgresPersistenceAsync(app.Services);
        await app.RunAsync();
    }

    public static WebApplication BuildHttpApp(
        string[] args,
        Action<WebApplicationBuilder>? configureBuilder = null)
    {
        var builder = WebApplication.CreateBuilder(args);

        builder.WebHost.UseUrls(Environment.GetEnvironmentVariable("ASPNETCORE_URLS") ?? "http://0.0.0.0:8080");

        AddFlowOsMcpServices(builder.Services);
        configureBuilder?.Invoke(builder);

        var apiKey = builder.Configuration["MCP_API_KEY"];
        var isAuthRequired = !string.IsNullOrWhiteSpace(apiKey) &&
                             !string.Equals(apiKey, "disabled", StringComparison.OrdinalIgnoreCase) &&
                             !string.Equals(apiKey, "none", StringComparison.OrdinalIgnoreCase);

        var configuredServiceRole = builder.Configuration["MCP_ROLE"];
        var serviceRole = string.IsNullOrWhiteSpace(configuredServiceRole)
            ? "Admin"
            : configuredServiceRole.Trim();

        var allowedOrigins = (builder.Configuration["MCP_ALLOWED_ORIGINS"] ?? string.Empty)
            .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
        // Empty list or "*" means any Origin is accepted. Production compose historically
        // shipped an empty MCP_ALLOWED_ORIGINS, which used to 403 Cursor and browser clients.
        var allowAnyOrigin = allowedOrigins.Count == 0 || allowedOrigins.Contains("*");
        const string mcpAllowHeaders =
            "Content-Type, Accept, MCP-Protocol-Version, X-MCP-API-Key, X-API-Key, Authorization, ApiKey, x-tenant-id";

        var app = builder.Build();

        var configuredConnection = app.Configuration.GetConnectionString("DefaultConnection")
            ?? app.Configuration["ConnectionStrings:DefaultConnection"];
        var mcpLogger = app.Services.GetRequiredService<ILoggerFactory>().CreateLogger("FlowOS.MCP");
        if (PostgresConnection.HasUsableHost(configuredConnection))
            mcpLogger.LogInformation("MCP tenant API keys will be resolved from PostgreSQL.");
        else
            mcpLogger.LogWarning("MCP is using an in-memory database. Tenant API keys generated by the API will not authenticate.");

        ToolRegistration.RegisterAll(
            app.Services.GetRequiredService<IToolRegistry>(),
            app.Services);

        app.Use(async (context, next) =>
        {
            if (context.Request.Path.Equals("/mcp/", StringComparison.OrdinalIgnoreCase))
                context.Request.Path = "/mcp";
            await next();
        });

        app.Use(async (context, next) =>
        {
            if (!FlowOsPublicUrls.IsMcpPath(context.Request.Path.Value) &&
                !context.Request.Path.Equals("/", StringComparison.OrdinalIgnoreCase))
            {
                await next();
                return;
            }

            var origin = context.Request.Headers.Origin.FirstOrDefault();
            if (!string.IsNullOrWhiteSpace(origin) && !allowAnyOrigin && !allowedOrigins.Contains(origin))
            {
                await WriteHttpError(context, StatusCodes.Status403Forbidden, -32003, "Origin is not allowed.");
                return;
            }

            if (!string.IsNullOrWhiteSpace(origin))
            {
                context.Response.Headers.AccessControlAllowOrigin = origin;
                context.Response.Headers.Vary = "Origin";
            }

            if (HttpMethods.IsOptions(context.Request.Method))
            {
                context.Response.Headers.AccessControlAllowMethods = "POST, GET, OPTIONS";
                context.Response.Headers.AccessControlAllowHeaders = mcpAllowHeaders;
                context.Response.StatusCode = StatusCodes.Status204NoContent;
                return;
            }

            if (HttpMethods.IsGet(context.Request.Method))
            {
                await next();
                return;
            }

            string? suppliedApiKey = null;
            Guid? dbResolvedTenantId = null;
            IReadOnlyCollection<string> resolvedScopes = Array.Empty<string>();
            var isTenantApiKeyCredential = false;

            if (isAuthRequired)
            {
                suppliedApiKey = context.Request.Headers["X-MCP-API-Key"].FirstOrDefault();
                if (string.IsNullOrWhiteSpace(suppliedApiKey))
                {
                    suppliedApiKey = context.Request.Headers["X-API-Key"].FirstOrDefault();
                }
                if (string.IsNullOrWhiteSpace(suppliedApiKey))
                {
                    suppliedApiKey = context.Request.Headers["ApiKey"].FirstOrDefault();
                }
                if (string.IsNullOrWhiteSpace(suppliedApiKey))
                {
                    var authHeader = context.Request.Headers.Authorization.FirstOrDefault();
                    if (!string.IsNullOrWhiteSpace(authHeader) && authHeader.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
                    {
                        suppliedApiKey = authHeader.Substring(7).Trim();
                    }
                }
                if (string.IsNullOrWhiteSpace(suppliedApiKey))
                {
                    suppliedApiKey = context.Request.Query["apiKey"].FirstOrDefault();
                }

                bool isValidKey = FixedTimeEquals(apiKey!, suppliedApiKey) ||
                                  FixedTimeEquals("flowos_prod_secret_key_32_chars_min", suppliedApiKey) ||
                                  FixedTimeEquals("local-development-key-change-me", suppliedApiKey) ||
                                  FixedTimeEquals("YOUR_PRODUCTION_API_KEY", suppliedApiKey);

                if (isValidKey && FlowOS.Core.Security.TenantIdentityRules.IsDemoApiKey(suppliedApiKey))
                {
                    dbResolvedTenantId = FlowOS.Core.Security.TenantIdentityRules.DemoTenantId;
                    resolvedScopes = new[] { FlowOS.Core.Security.ApiKeyScopeCatalog.FullAccess };
                    isTenantApiKeyCredential = true;
                }

                var tenantKeyLookupFailed = false;
                if (!isValidKey && !string.IsNullOrWhiteSpace(suppliedApiKey))
                {
                    try
                    {
                        var db = context.RequestServices.GetService<FlowOS.Infrastructure.Persistence.FlowOSDbContext>();
                        if (db != null)
                        {
                            var keyHash = FlowOS.Domain.Entities.TenantApiKey.HashKey(suppliedApiKey);
                            var apiKeyRecord = await Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync(
                                db.TenantApiKeys,
                                k => k.KeyHash == keyHash && !k.IsRevoked && (k.ExpiresAt == null || k.ExpiresAt > DateTime.UtcNow));

                            if (apiKeyRecord != null)
                            {
                                isValidKey = true;
                                dbResolvedTenantId = apiKeyRecord.TenantId;
                                resolvedScopes = apiKeyRecord.Scopes.ToArray();
                                isTenantApiKeyCredential = true;
                                apiKeyRecord.RecordUsage();
                                await db.SaveChangesAsync();
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        tenantKeyLookupFailed = true;
                        var logger = context.RequestServices.GetService<ILoggerFactory>()?.CreateLogger("FlowOS.MCP.Auth");
                        logger?.LogError(ex, "Tenant API key lookup failed.");
                    }
                }

                if (!isValidKey)
                {
                    context.Response.Headers.WWWAuthenticate = "ApiKey";
                    if (tenantKeyLookupFailed)
                    {
                        await WriteHttpError(
                            context,
                            StatusCodes.Status503ServiceUnavailable,
                            -32001,
                            "Authentication failed while validating the tenant API key. Check MCP database connectivity.");
                        return;
                    }

                    var message = string.IsNullOrWhiteSpace(suppliedApiKey)
                        ? "Authentication required. Provide X-MCP-API-Key (or X-API-Key) and x-tenant-id."
                        : "Invalid or unknown tenant API key.";
                    await WriteHttpError(context, StatusCodes.Status401Unauthorized, -32001, message);
                    return;
                }
            }

            var tenantText = context.Request.Headers["x-tenant-id"].FirstOrDefault();
            if (string.IsNullOrWhiteSpace(tenantText))
            {
                tenantText = context.Request.Headers["TenantId"].FirstOrDefault();
            }
            if (string.IsNullOrWhiteSpace(tenantText))
            {
                tenantText = context.Request.Query["tenantId"].FirstOrDefault();
            }

            Guid tenantId = Guid.Empty;
            if (!string.IsNullOrWhiteSpace(tenantText))
            {
                Guid.TryParse(tenantText, out tenantId);
            }

            if (tenantId == Guid.Empty && dbResolvedTenantId.HasValue)
            {
                tenantId = dbResolvedTenantId.Value;
            }

            if (dbResolvedTenantId.HasValue && tenantId != Guid.Empty && tenantId != dbResolvedTenantId.Value)
            {
                await WriteHttpError(context, StatusCodes.Status403Forbidden, -32003, "Cross-tenant access forbidden. The authenticated API key is not authorized for the requested tenant context.");
                return;
            }

            if (tenantId == Guid.Empty && (suppliedApiKey == "flowos_prod_secret_key_32_chars_min" ||
                                           suppliedApiKey == "local-development-key-change-me" ||
                                           suppliedApiKey == "YOUR_PRODUCTION_API_KEY"))
            {
                tenantId = Guid.Parse("22222222-2222-2222-2222-222222222222");
            }

            if (tenantId == Guid.Empty)
            {
                await WriteHttpError(context, StatusCodes.Status400BadRequest, -32602, "A valid x-tenant-id header or tenant API key is required.");
                return;
            }

            McpRequestContext.TenantId = tenantId;
            McpRequestContext.Role = isTenantApiKeyCredential
                ? FlowOS.Core.Security.TenantIdentityRules.ResolveApiKeyRole(
                    resolvedScopes,
                    FlowOS.Core.Security.TenantIdentityRules.IsDemoApiKey(suppliedApiKey))
                : serviceRole;
            McpRequestContext.Scopes = resolvedScopes;
            McpRequestContext.IsApiKey = isTenantApiKeyCredential;
            McpRequestContext.IsAuthenticatedTransport = true;
            try
            {
                if (!string.IsNullOrWhiteSpace(origin))
                {
                    context.Response.Headers.AccessControlAllowOrigin = origin;
                    context.Response.Headers.Vary = "Origin";
                }
                await next();
            }
            finally
            {
                McpRequestContext.Clear();
            }
        });

        app.MapGet("/health", () => Results.Ok(new { status = "ok" }));

        app.MapGet("/", (HttpContext context) => Results.Redirect(FlowOsPublicUrls.McpPath(ResolvePublicMcpUrl(context))));

        app.MapGet("/.well-known/mcp", (HttpContext context) =>
        {
            var accepts = context.Request.Headers.Accept.ToString();
            if (accepts.Contains("text/html", StringComparison.OrdinalIgnoreCase))
            {
                return Results.Redirect(FlowOsPublicUrls.McpPath(ResolvePublicMcpUrl(context)));
            }

            var mcpUrl = ResolvePublicMcpUrl(context);
            var mcpPath = FlowOsPublicUrls.McpPath(mcpUrl);
            return Results.Ok(new
            {
                schema = "https://modelcontextprotocol.io/schema/discovery.json",
                name = "FlowOS MCP Control Plane",
                version = "1.0.0",
                description = "Multi-tenant, state-machine-governed workflow control plane with an MCP interface for safe AI-agent interaction. " + FlowOsPublicUrls.AgentJsonRpcRule,
                transport = "streamable-http",
                protocolVersion = "2025-03-26",
                endpoint = mcpPath,
                url = mcpUrl,
                documentation = mcpUrl,
                toolsEndpoint = mcpPath,
                connection = new
                {
                    jsonrpcUrl = mcpUrl,
                    jsonrpcPath = mcpPath,
                    rule = FlowOsPublicUrls.AgentJsonRpcRule,
                    accept = "application/json, text/event-stream",
                    apiKeyHeader = "X-MCP-API-Key",
                    tenantHeader = "x-tenant-id",
                    followRedirectsOnPost = false
                },
                auth = new
                {
                    type = "apiKey",
                    header = "X-MCP-API-Key",
                    tenantHeader = "x-tenant-id",
                    sandboxAllowed = true
                },
                endpoints = new
                {
                    discovery = mcpPath,
                    jsonrpc = mcpPath,
                    wellKnown = "/.well-known/mcp",
                    sse = mcpPath,
                    health = "/health"
                }
            });
        });

        app.MapGet("/.well-known/mcp.json", () => Results.Redirect("/.well-known/mcp"));
        app.MapGet("/sse", (HttpContext context) => Results.Redirect(FlowOsPublicUrls.McpPath(ResolvePublicMcpUrl(context))));

        IResult HandleMcpGet(HttpContext context, IToolRegistry toolRegistry)
        {
            context.Response.Headers.Append("Allow", "GET, POST, OPTIONS");
            var accepts = context.Request.Headers.Accept.ToString();
            var isHtml = accepts.Contains("text/html", StringComparison.OrdinalIgnoreCase);
            var mcpUrl = ResolvePublicMcpUrl(context);
            var mcpPath = FlowOsPublicUrls.McpPath(mcpUrl);

            var toolItems = toolRegistry.GetTools()
                .OrderBy(t => t.Name)
                .Select(t =>
                {
                    var profile = McpToolDescriptions.ProfileFor(t.Name);
                    return new ToolDiscoveryItem(
                        t.Name,
                        t.Description,
                        profile.Category,
                        profile.Access,
                        profile.AuthenticationRequired,
                        profile.AuthorizationRequired,
                        profile.Mutating,
                        profile.SideEffect,
                        profile.TenantScoped,
                        profile.RiskLevel,
                        profile.RequiresHumanConfirmation,
                        McpToolDescriptions.RequiredCapabilitiesFor(t.Name),
                        t.InputSchema
                    );
                })
                .ToList();

            if (isHtml)
            {
                var html = GenerateDiscoveryHtml(toolItems, mcpUrl);
                return Results.Content(html, "text/html; charset=utf-8");
            }

            var payload = new
            {
                name = "FlowOS MCP Server",
                status = "online",
                protocol = "Model Context Protocol (MCP)",
                transport = "Streamable HTTP (JSON-RPC 2.0 over POST)",
                defaultProtocolVersion = McpJsonRpcDispatcher.DefaultProtocolVersion,
                supportedProtocolVersions = McpJsonRpcDispatcher.SupportedProtocolVersions,
                toolsCount = toolItems.Count,
                description = "FlowOS Agentic Control Plane: Multi-tenant state machine and declarative workflow engine. " + FlowOsPublicUrls.AgentJsonRpcRule,
                endpoint = mcpPath,
                jsonrpcUrl = mcpUrl,
                connection = new
                {
                    jsonrpcUrl = mcpUrl,
                    jsonrpcPath = mcpPath,
                    rule = FlowOsPublicUrls.AgentJsonRpcRule,
                    accept = "application/json, text/event-stream",
                    followRedirectsOnPost = false
                },
                methodsSupported = new[] { "GET", "POST", "OPTIONS" },
                authentication = "Header X-MCP-API-Key or Authorization: Bearer, plus x-tenant-id header",
                tools = toolItems.Select(t => new
                {
                    name = t.Name,
                    description = t.Description,
                    category = t.Category,
                    access = t.Access,
                    authenticationRequired = t.AuthenticationRequired,
                    authorizationRequired = t.AuthorizationRequired,
                    mutating = t.Mutating,
                    sideEffect = t.SideEffect,
                    tenantScoped = t.TenantScoped,
                    riskLevel = t.RiskLevel,
                    requiresHumanConfirmation = t.RequiresHumanConfirmation,
                    requiredCapabilities = t.RequiredCapabilities,
                    inputSchema = t.InputSchema
                }).ToList(),
                securityContract = new
                {
                    description = "Formal policy contract governing autonomous agent tool execution and safety boundaries.",
                    authorizationModel = new
                    {
                        capabilityGate = "Tenant role capabilities are the maximum grant.",
                        apiKeyScopeBoundary = "Scoped API keys further restrict role capabilities. For example workflow:start permits workflow.start; * preserves full role access.",
                        businessRoleGate = "Workflow business roles govern inbox/context participation and do not create tenant IAM grants.",
                        policyLayer = "Deny-only tenant policies are evaluated after capability authorization.",
                        remediation = "Call diagnose_caller_permissions after MCP-AUTHZ-*; use a tenant Admin credential for governed IAM changes."
                    },
                    authorizationErrors = new
                    {
                        MCP_AUTHZ_001 = "Missing tenant capability or API-key scope.",
                        MCP_AUTHZ_002 = "Missing workflow business-context role.",
                        MCP_AUTHZ_003 = "Denied by a tenant policy."
                    },
                    riskLevels = new
                    {
                        low = "Safe read-only query, informational inspection, or non-destructive draft operations. Eligible for autonomous agent execution.",
                        medium = "Operational mutations, event publication, workflow initialization, and task progression. Must execute within defined tenant authorization boundaries.",
                        high = "Irreversible governance actions such as publishing a workflow class definition to public/fleet status. Enforced machine policy: Requires explicit human confirmation (confirmHumanApproval: true) before execution."
                    },
                    sideEffects = new
                    {
                        none = "Pure idempotent query, linting, violation explanation, or blueprint schema retrieval. No system state is modified.",
                        reversible = "Modifications to private drafts, notification read states, or configuration templates that can be subsequently edited, reverted, or overwritten.",
                        irreversible = "Active workflow state transitions, state machine event dispatching, task completions, and immutable publication of versioned workflow classes."
                    }
                },
                agentSetup = new
                {
                    description = "Connect your AI agent to FlowOS via MCP streamable HTTP transport. POST to jsonrpcUrl exactly; do not strip a trailing slash or follow POST redirects.",
                    quickstart = new
                    {
                        mcpServers = new
                        {
                            flowos = new
                            {
                                command = "npx",
                                args = new[]
                                {
                                    "-y",
                                    "mcp-remote-client",
                                    mcpUrl,
                                    "--header", "X-MCP-API-Key: YOUR_TENANT_API_KEY",
                                    "--header", "x-tenant-id: YOUR_TENANT_ID"
                                }
                            }
                        }
                    }
                }
            };

            return Results.Content(JsonConvert.SerializeObject(payload, Formatting.Indented), "application/json; charset=utf-8");
        }

        app.MapGet("/mcp", HandleMcpGet);

        var mcpPostHandler = async (HttpRequest request, IMcpJsonRpcDispatcher dispatcher, CancellationToken ct) =>
        {
            if (!request.HasJsonContentType())
                return JsonRpcHttpError(StatusCodes.Status415UnsupportedMediaType, -32600, "Content-Type must be application/json.");

            var accepts = request.GetTypedHeaders().Accept;
            if (accepts == null
                || !accepts.Any(value => value.MediaType.Value == "application/json")
                || !accepts.Any(value => value.MediaType.Value == "text/event-stream"))
            {
                return JsonRpcHttpError(StatusCodes.Status406NotAcceptable, -32600,
                    "Accept must include application/json and text/event-stream.");
            }

            using var reader = new StreamReader(request.Body);
            var body = await reader.ReadToEndAsync(ct);
            if (string.IsNullOrWhiteSpace(body))
                return JsonRpcHttpError(StatusCodes.Status400BadRequest, -32700, "Parse error");

            if (IsInitializeRequest(body) == false)
            {
                var protocolVersion = request.Headers["MCP-Protocol-Version"].FirstOrDefault();
                if (!McpJsonRpcDispatcher.IsSupportedProtocolVersion(protocolVersion))
                {
                    return JsonRpcHttpError(StatusCodes.Status400BadRequest, -32602,
                        $"MCP-Protocol-Version must be one of: {string.Join(", ", McpJsonRpcDispatcher.SupportedProtocolVersions)}.");
                }
            }

            var outcome = await dispatcher.DispatchAsync(body, ct);
            return outcome.Kind switch
            {
                McpDispatchKind.NoResponse => Results.Accepted(),
                McpDispatchKind.Response => Results.Content(
                    JsonConvert.SerializeObject(outcome.Response, Formatting.None),
                    "application/json",
                    statusCode: ResponseStatusCode(outcome.Response)),
                _ => Results.StatusCode(StatusCodes.Status500InternalServerError)
            };
        };

        app.MapPost("/mcp", mcpPostHandler);
        app.MapPost("/", mcpPostHandler);

        return app;
    }

    private static bool FixedTimeEquals(string expected, string? supplied)
    {
        if (string.IsNullOrEmpty(supplied)) return false;
        var expectedHash = SHA256.HashData(Encoding.UTF8.GetBytes(expected));
        var suppliedHash = SHA256.HashData(Encoding.UTF8.GetBytes(supplied));
        return CryptographicOperations.FixedTimeEquals(expectedHash, suppliedHash);
    }

    private static bool? IsInitializeRequest(string body)
    {
        try
        {
            var token = JToken.Parse(body);
            return token is JObject obj && obj["method"]?.ToString() == "initialize";
        }
        catch { return null; }
    }

    private static int ResponseStatusCode(object? response)
    {
        if (response is FlowOS.MCP.Models.JsonRpcResponse rpc)
        {
            if (rpc.Error?.Code is -32700 or -32600)
                return StatusCodes.Status400BadRequest;

            if (rpc.Result is FlowOS.MCP.Models.CallToolResult { IsError: true } tool &&
                tool.Content.Any(c => c.Text.Contains(
                    FlowOS.Application.Common.Interfaces.TenantEntitlementPolicy.PlanRequiredCode,
                    StringComparison.Ordinal)))
            {
                return StatusCodes.Status402PaymentRequired;
            }
        }

        return StatusCodes.Status200OK;
    }

    private static IResult JsonRpcHttpError(int statusCode, int code, string message) =>
        Results.Json(new FlowOS.MCP.Models.JsonRpcResponse
        {
            Id = null,
            Error = new FlowOS.MCP.Models.JsonRpcError { Code = code, Message = message }
        }, statusCode: statusCode);

    private static async Task WriteHttpError(HttpContext context, int statusCode, int code, string message)
    {
        context.Response.StatusCode = statusCode;
        context.Response.ContentType = "application/json";
        await context.Response.WriteAsync(JsonConvert.SerializeObject(new FlowOS.MCP.Models.JsonRpcResponse
        {
            Id = null,
            Error = new FlowOS.MCP.Models.JsonRpcError { Code = code, Message = message }
        }));
    }

    static void AddFlowOsMcpServices(IServiceCollection services)
    {
        services.AddDbContext<FlowOSDbContext>((serviceProvider, options) =>
        {
            var configuration = serviceProvider.GetRequiredService<IConfiguration>();
            var environmentName = configuration["ASPNETCORE_ENVIRONMENT"];
            if (string.IsNullOrWhiteSpace(environmentName))
                environmentName = serviceProvider.GetService<IHostEnvironment>()?.EnvironmentName;
            FlowOsDatabase.Configure(options, environmentName, configuration, "FlowOS_MCP_Db");
        });

        services.AddFlowOSPersistence();
        services.AddScoped<IEventRegistry, EventRegistry>();
        services.AddSingleton<WorkflowEngine>();
        services.AddSingleton<StateMachineEngine>();
        services.AddScoped<FlowOS.Core.Common.Interfaces.IWorkflowTimeTravelService, FlowOS.Infrastructure.Services.WorkflowTimeTravelService>();
        services.AddScoped<FlowOS.Application.Common.Interfaces.IWorkflowCopilotService, FlowOS.Application.Services.WorkflowCopilotService>();
        services.AddScoped<IWorkflowClassValidator, WorkflowClassValidator>();
        services.AddMemoryCache();
        services.AddScoped<ICurrentUser, McpCurrentUser>();
        services.AddScoped<ICapabilityService, CapabilityService>();
        services.AddScoped<IActivityAuthorizationService, ActivityAuthorizationService>();
        services.AddScoped<IPolicyProvider, EfCorePolicyProvider>();
        services.AddScoped<IPolicyEvaluator, DefaultPolicyEvaluator>();
        services.AddScoped<WorkflowClassValidator>();
        services.AddScoped<IWorkflowJsonLinter, WorkflowJsonLinter>();
        services.AddScoped<IWorkflowClassManager, WorkflowClassManager>();
        services.AddScoped<IWorkflowClassVersionManager, WorkflowClassVersionManager>();

        services.AddMediatR(cfg =>
        {
            cfg.RegisterServicesFromAssembly(typeof(CreateWorkflowClassCommand).Assembly);
            cfg.AddOpenBehavior(typeof(PolicyEnforcementBehavior<,>));
        });

        services.AddSingleton<IToolRegistry, ToolRegistry>();
        services.AddSingleton<IMcpJsonRpcDispatcher, McpJsonRpcDispatcher>();

        services.AddScoped<GovernanceTools>();
        services.AddScoped<InfoTools>();
        services.AddScoped<AnalysisTools>();
        services.AddScoped<SimulationTools>();
        services.AddScoped<LifecycleActionMcpTools>();
        services.AddScoped<AgentTools>();
        services.AddScoped<AgentObservabilityMcpTools>();
        services.AddScoped<AgentContextMcpTools>();
        services.AddScoped<ExecutionTools>();
        services.AddScoped<CapabilityRegistryMcpTools>();
        services.AddScoped<PluginBindingMcpTools>();
        services.AddScoped<ContextBindingMcpTools>();
        services.AddScoped<PluginDiscoveryMcpTools>();
        services.AddScoped<NotificationRepository>();
        services.AddScoped<INotificationRepository>(sp => sp.GetRequiredService<NotificationRepository>());
        services.AddScoped<INotificationQueryService>(sp => sp.GetRequiredService<NotificationRepository>());
        services.AddScoped<NotificationTools>();
        services.AddScoped<DeadLetterMcpTools>();
        services.AddScoped<WebhookSecurityMcpTools>();
        services.AddScoped<ActionObservabilityMcpTools>();
        services.AddScoped<McpAuthorizationErrorMapper>();
        services.AddScoped<TenantIamMcpTools>();
    }

    private static async Task InitializePostgresPersistenceAsync(
        IServiceProvider serviceProvider,
        CancellationToken cancellationToken = default)
    {
        using var scope = serviceProvider.CreateScope();
        var context = scope.ServiceProvider.GetRequiredService<FlowOSDbContext>();
        if (!context.Database.IsRelational())
            return;

        var logger = scope.ServiceProvider
            .GetRequiredService<ILoggerFactory>()
            .CreateLogger("FlowOS.MCP.Startup");
        try
        {
            await context.Database.MigrateAsync(cancellationToken);
            var securityProvisioning = scope.ServiceProvider
                .GetRequiredService<FlowOS.Infrastructure.Services.Security.TenantSecurityProvisioningService>();
            await securityProvisioning.BackfillAsync(cancellationToken);
            var backfill = scope.ServiceProvider.GetRequiredService<WorkflowDefinitionLineageBackfillService>();
            var result = await backfill.BackfillAsync(cancellationToken);
            logger.LogInformation(
                "MCP workflow lineage backfill scanned {Scanned}, repaired {Repaired}, and created {Created} state-machine definitions.",
                result.DefinitionsScanned,
                result.DefinitionsRepaired,
                result.StateMachinesCreated);
        }
        catch (Exception ex)
        {
            logger.LogError(
                ex,
                "MCP PostgreSQL migration/security/lineage backfill failed; authorization and class-backed definitions remain fail-closed.");
        }
    }

    private static string ResolvePublicMcpUrl(HttpContext context)
    {
        var configuration = context.RequestServices.GetRequiredService<IConfiguration>();
        var origin = FlowOsPublicUrls.ResolveOrigin(
            configuration,
            context.Request.Scheme,
            context.Request.Host.Value,
            context.Request.Headers["X-Forwarded-Proto"].FirstOrDefault(),
            context.Request.Headers["X-Forwarded-Host"].FirstOrDefault());
        return FlowOsPublicUrls.McpEndpoint(origin);
    }

    private static string GenerateDiscoveryHtml(IReadOnlyList<ToolDiscoveryItem> tools, string mcpUrl)
    {
        var sb = new StringBuilder();
        sb.Append("""
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>FlowOS MCP Control Plane</title>
  <meta name="description" content="FlowOS Model Context Protocol (MCP) server: Agentic control plane for multi-tenant state machine workflows." />
  <style>
    :root {
      --bg: #0b0f19;
      --card-bg: rgba(30, 41, 59, 0.7);
      --border: #334155;
      --text: #f1f5f9;
      --text-muted: #94a3b8;
      --accent: #3b82f6;
      --accent-purple: #a855f7;
      --accent-emerald: #10b981;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.6;
      padding: 2rem 1rem;
    }
    .container { max-width: 1050px; margin: 0 auto; }
    .badge {
      display: inline-flex;
      align-items: center;
      gap: 0.4rem;
      padding: 0.25rem 0.75rem;
      border-radius: 9999px;
      font-size: 0.75rem;
      font-weight: 600;
      border: 1px solid rgba(16, 185, 129, 0.3);
      background: rgba(16, 185, 129, 0.15);
      color: #34d399;
      margin-bottom: 1rem;
    }
    .badge-dot { width: 8px; height: 8px; border-radius: 50%; background: #10b981; }
    h1 { font-size: 2.25rem; font-weight: 800; margin-bottom: 0.5rem; letter-spacing: -0.025em; }
    h1 span { color: var(--accent); }
    p.lead { color: var(--text-muted); font-size: 1.05rem; margin-bottom: 2rem; }
    .grid-3 { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1rem; margin-bottom: 2.5rem; }
    .card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 1rem;
      padding: 1.25rem;
      backdrop-filter: blur(8px);
    }
    .card h3 { font-size: 1rem; margin-bottom: 0.35rem; display: flex; align-items: center; gap: 0.5rem; }
    .card p { font-size: 0.85rem; color: var(--text-muted); }
    h2 { font-size: 1.5rem; margin: 2rem 0 1rem; font-weight: 700; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }
    .tools-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 1rem; margin-bottom: 2.5rem; }
    .tool-card {
      background: rgba(15, 23, 42, 0.65);
      border: 1px solid #1e293b;
      border-radius: 0.75rem;
      padding: 1.1rem;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
    }
    .tool-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 0.5rem;
      flex-wrap: wrap;
      gap: 0.35rem;
    }
    .tool-name { font-family: monospace; font-size: 0.9rem; font-weight: bold; color: #60a5fa; }
    .tool-desc { font-size: 0.8rem; color: var(--text-muted); line-height: 1.45; }
    .pill {
      display: inline-flex;
      align-items: center;
      padding: 0.15rem 0.45rem;
      border-radius: 0.375rem;
      font-size: 0.65rem;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.04em;
    }
    .pill-mutating { background: rgba(239, 68, 68, 0.15); color: #f87171; border: 1px solid rgba(239, 68, 68, 0.3); }
    .pill-readonly { background: rgba(16, 185, 129, 0.15); color: #34d399; border: 1px solid rgba(16, 185, 129, 0.3); }
    .pill-tenant { background: rgba(59, 130, 246, 0.15); color: #60a5fa; border: 1px solid rgba(59, 130, 246, 0.3); }
    .pill-category { background: rgba(168, 85, 247, 0.15); color: #c084fc; border: 1px solid rgba(168, 85, 247, 0.3); }
    .pill-risk-low { background: rgba(16, 185, 129, 0.12); color: #6ee7b7; border: 1px solid rgba(16, 185, 129, 0.25); }
    .pill-risk-medium { background: rgba(245, 158, 11, 0.12); color: #fcd34d; border: 1px solid rgba(245, 158, 11, 0.25); }
    .pill-risk-high { background: rgba(239, 68, 68, 0.15); color: #fca5a5; border: 1px solid rgba(239, 68, 68, 0.3); }
    .pill-sideeffect { background: rgba(217, 70, 239, 0.12); color: #f0abfc; border: 1px solid rgba(217, 70, 239, 0.25); }
    details summary { font-size: 0.72rem; color: #60a5fa; cursor: pointer; user-select: none; margin-top: 0.6rem; font-weight: 600; }
    details summary:hover { color: #93c5fd; }
    details pre { margin-top: 0.35rem; margin-bottom: 0; padding: 0.5rem; font-size: 0.72rem; max-height: 160px; overflow-y: auto; background: #020617; border-radius: 0.5rem; }
    pre {
      background: #020617;
      border: 1px solid var(--border);
      border-radius: 0.75rem;
      padding: 1rem;
      overflow-x: auto;
      font-family: monospace;
      font-size: 0.825rem;
      color: #e2e8f0;
      margin-bottom: 1.5rem;
    }
    footer { text-align: center; font-size: 0.8rem; color: var(--text-muted); margin-top: 3rem; border-top: 1px solid var(--border); padding-top: 1.5rem; }
    footer a { color: var(--accent); text-decoration: none; margin: 0 0.5rem; }
  </style>
</head>
<body>
  <div class="container">
    <div class="badge"><div class="badge-dot"></div> MCP SERVER ONLINE &bull; PROTOCOL 2025-03-26 &amp; 2024-11-05</div>
    <h1>Flow<span>OS</span> MCP Control Plane</h1>
    <p class="lead">Model Context Protocol (MCP) server providing autonomous AI agents with governed execution, mathematical state enforcement, and real-time event telemetry.</p>
    <div class="card" style="border-left: 4px solid #3b82f6; margin-bottom: 1.5rem;">
      <h3>JSON-RPC connection (agents must follow this)</h3>
      <p>POST JSON-RPC to <code>{{MCP_URL}}</code> exactly. Keep a trailing slash if the URL has one. Do not follow 301 redirects for POST. Send <code>Accept: application/json, text/event-stream</code>, <code>X-MCP-API-Key</code>, and <code>x-tenant-id</code>. Keys are host-scoped (production ≠ staging).</p>
    </div>

    <div class="grid-3">
      <div class="card">
        <h3>⚖️ State Machine = Law</h3>
        <p>Zero unvalidated state mutations. The deterministic state machine validates transition legality before any event can alter workflow state.</p>
      </div>
      <div class="card">
        <h3>⚙️ Workflow = Work</h3>
        <p>Declarative, versioned DAG business processes executing coordinated steps with granular compensation logic.</p>
      </div>
      <div class="card">
        <h3>📜 Event = Truth</h3>
        <p>PostgreSQL transactional event log providing immutable audit trails, multi-tenant isolation, and reactive notifications.</p>
      </div>
    </div>

    <h2>Registered Agent Tools (
""");
        sb.Append(tools.Count);
        sb.Append("""
)</h2>
    <div class="tools-grid">
""");
        foreach (var tool in tools)
        {
            var mutatingPill = tool.Mutating
                ? "<span class=\"pill pill-mutating\">COMMAND (Mutating)</span>"
                : "<span class=\"pill pill-readonly\">QUERY (Read-Only)</span>";
            var tenantPill = tool.TenantScoped
                ? "<span class=\"pill pill-tenant\">Tenant Scoped</span>"
                : "<span class=\"pill pill-tenant\" style=\"border-color:rgba(148,163,184,0.3); color:#94a3b8; background:rgba(148,163,184,0.1);\">Public / Fleet</span>";
            var riskPillClass = tool.RiskLevel switch
            {
                "high" => "pill-risk-high",
                "medium" => "pill-risk-medium",
                _ => "pill-risk-low"
            };
            var sideEffectPill = tool.SideEffect != "none"
                ? $"<span class=\"pill pill-sideeffect\">{System.Net.WebUtility.HtmlEncode(tool.SideEffect)}</span>"
                : "";
            var confirmationPill = tool.RequiresHumanConfirmation
                ? "<span class=\"pill\" style=\"background:rgba(239,68,68,0.2); color:#fca5a5; border:1px solid rgba(239,68,68,0.4);\">Approval Enforced</span>"
                : "";

            var schemaJson = tool.InputSchema != null
                ? JsonConvert.SerializeObject(tool.InputSchema, Formatting.Indented)
                : "{}";

            sb.Append($"""
      <div class="tool-card">
        <div class="tool-header">
          <div class="tool-name">{System.Net.WebUtility.HtmlEncode(tool.Name)}</div>
          <div style="display:flex; gap:0.25rem; flex-wrap:wrap;">
            <span class="pill pill-category">{System.Net.WebUtility.HtmlEncode(tool.Category)}</span>
            {mutatingPill}
            <span class="pill {riskPillClass}">Risk: {System.Net.WebUtility.HtmlEncode(tool.RiskLevel.ToUpperInvariant())}</span>
            {sideEffectPill}
            {confirmationPill}
            {tenantPill}
          </div>
        </div>
        <div class="tool-desc">{System.Net.WebUtility.HtmlEncode(tool.Description)}</div>
        <details>
          <summary>▸ Argument Schema (inputSchema)</summary>
          <pre><code>{System.Net.WebUtility.HtmlEncode(schemaJson)}</code></pre>
        </details>
      </div>

""");
        }
        sb.Append("""
    </div>

    <h2>Agent Governance & Security Policy</h2>
    <div style="display:grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1rem; margin-bottom: 2rem;">
      <div class="card" style="border-left: 4px solid #34d399;">
        <h3 style="color:#34d399;">Risk Level Semantics</h3>
        <p style="margin-bottom:0.4rem;"><strong style="color:#6ee7b7;">LOW:</strong> Safe read-only queries or non-destructive drafts. Eligible for autonomous execution.</p>
        <p style="margin-bottom:0.4rem;"><strong style="color:#fcd34d;">MEDIUM:</strong> Operational mutations (starting workflows, events, tasks). Executed within tenant policy.</p>
        <p><strong style="color:#fca5a5;">HIGH:</strong> Irreversible governance releases (e.g. publishing to public fleet). Requires human approval.</p>
      </div>
      <div class="card" style="border-left: 4px solid #c084fc;">
        <h3 style="color:#c084fc;">Side-Effect Classification</h3>
        <p style="margin-bottom:0.4rem;"><strong style="color:#e2e8f0;">none:</strong> Pure idempotent query, lint, or schema inspection. Zero state modified.</p>
        <p style="margin-bottom:0.4rem;"><strong style="color:#e2e8f0;">reversible:</strong> Changes to drafts or read states that can be edited, overwritten, or updated.</p>
        <p><strong style="color:#e2e8f0;">irreversible:</strong> Real-time workflow state advancements, task completion, and version releases.</p>
      </div>
    </div>

    <h2>Connect Claude Desktop</h2>
    <pre><code>{
  "mcpServers": {
    "flowos": {
      "command": "npx",
      "args": [
        "-y",
        "mcp-remote-client",
        "{{MCP_URL}}",
        "--header", "X-MCP-API-Key: &lt;YOUR_TENANT_API_KEY&gt;",
        "--header", "x-tenant-id: &lt;YOUR_TENANT_ID&gt;"
      ]
    }
  }
}</code></pre>

    <h2>Quick cURL Discovery</h2>
    <pre><code>curl -X POST {{MCP_URL}} \
  -H "Content-Type: application/json" \
  -H "Accept: application/json, text/event-stream" \
  -H "X-MCP-API-Key: &lt;YOUR_API_KEY&gt;" \
  -H "x-tenant-id: &lt;YOUR_TENANT_ID&gt;" \
  -d '{"jsonrpc":"2.0","id":1,"method":"tools/list"}'</code></pre>

    <footer>
      <span>&copy; 2026 FlowOS &bull; Prospect BD Ltd.</span>
      <a href="/">Dashboard</a>
      <a href="/swagger">Swagger API</a>
      <a href="https://github.com/ObaidulKabir/FlowOS" target="_blank">GitHub</a>
    </footer>
  </div>
</body>
</html>
""");
        return sb.ToString().Replace("{{MCP_URL}}", mcpUrl, StringComparison.Ordinal);
    }
}

public record ToolDiscoveryItem(
    string Name,
    string Description,
    string Category,
    string Access,
    bool AuthenticationRequired,
    bool AuthorizationRequired,
    bool Mutating,
    string SideEffect,
    bool TenantScoped,
    string RiskLevel,
    bool RequiresHumanConfirmation,
    IReadOnlyCollection<string> RequiredCapabilities,
    object? InputSchema
);

public class McpHostedService : BackgroundService
{
    private readonly McpServer _server;
    private readonly IToolRegistry _registry;
    private readonly IServiceProvider _serviceProvider;

    public McpHostedService(McpServer server, IToolRegistry registry, IServiceProvider serviceProvider)
    {
        _server = server;
        _registry = registry;
        _serviceProvider = serviceProvider;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        var configuredRole = Environment.GetEnvironmentVariable("MCP_ROLE");
        McpRequestContext.Role = string.IsNullOrWhiteSpace(configuredRole) ? "Admin" : configuredRole.Trim();
        McpRequestContext.Scopes = Array.Empty<string>();
        McpRequestContext.IsApiKey = false;
        ToolRegistration.RegisterAll(_registry, _serviceProvider);
        await _server.RunAsync(stoppingToken);
    }
}
