name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  deploy:
    name: Deploy to ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Update Code on Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -euo pipefail
            cd  ${{ secrets.APP_PATH }}
            git fetch origin
            git checkout -B main origin/main
            docker network create traefik-network || true

      - name: Build and Deploy Containers 
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22 
          script: |
            set -euo pipefail
            cd ${{ secrets.APP_PATH }}  
            docker compose -f docker-compose.prod.yml up --build -d
            docker builder prune --filter "until=12h" -f