name: CI
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]
jobs:     
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production 
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Update Code on Server
        uses: appleboy/ssh-action@b0a8f324e192469585a608d1f586061cf28a6571
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -euo pipefail
            cd  ${{ secrets.APP_PATH }}
            git fetch -p
            git checkout ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}

      - name: Build and Deploy Containers
        uses: appleboy/ssh-action@b0a8f324e192469585a608d1f586061cf28a6571
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -euo pipefail
            cd  ${{ secrets.APP_PATH }}
            docker compose -f docker-compose.test.yaml  down
            docker compose -f docker-compose.test.yaml up -d --build